[package]
name = "validator_http_api"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[lib]
name = "validator_http_api"
path = "src/lib.rs"

[dependencies]
warp_utils = { workspace = true }
warp = { workspace = true }

[dev-dependencies]
